export const EDITOR_CONST = {
  BREAKPOINTS: {
    SM: 640,
    MD: 768,
    LG: 1024,
    XLG: 1440,
  },
  TILE_WIDTH_CALC_NUMBER_A: 53,
  TILE_WIDTH_CALC_NUMBER_B: 51,
  TILE_WIDTH_CALC_NUMBER_C: 49,
  TILE_HEIGHT_CALC_NUMBER_A: 60,
  TILE_HEIGHT_CALC_NUMBER_B: 52,
};
